# Generated by Django 5.1.3 on 2024-11-26 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futzal_app', '0002_admin_foto_profil_lapangan_foto_lapangan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pemesanan',
            name='user',
        ),
        migrations.AddField(
            model_name='pemesanan',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='futzal_app.profile'),
        ),
        migrations.AddField(
            model_name='pemesanan',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='futzal_app.staff'),
        ),
    ]
